
/****** Object:  Database [estoque]    Script Date: 30/03/2025 19:26:06 ******/
CREATE DATABASE [estoque]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'estoque', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\estoque.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'estoque_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\estoque_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF

ALTER DATABASE [estoque] SET COMPATIBILITY_LEVEL = 160

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [estoque].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [estoque] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [estoque] SET ANSI_NULLS OFF 

ALTER DATABASE [estoque] SET ANSI_PADDING OFF 

ALTER DATABASE [estoque] SET ANSI_WARNINGS OFF 

ALTER DATABASE [estoque] SET ARITHABORT OFF 

ALTER DATABASE [estoque] SET AUTO_CLOSE OFF 

ALTER DATABASE [estoque] SET AUTO_SHRINK OFF 

ALTER DATABASE [estoque] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [estoque] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [estoque] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [estoque] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [estoque] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [estoque] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [estoque] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [estoque] SET  DISABLE_BROKER 

ALTER DATABASE [estoque] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [estoque] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [estoque] SET TRUSTWORTHY OFF 

ALTER DATABASE [estoque] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [estoque] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [estoque] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [estoque] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [estoque] SET RECOVERY SIMPLE 

ALTER DATABASE [estoque] SET  MULTI_USER 

ALTER DATABASE [estoque] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [estoque] SET DB_CHAINING OFF 

ALTER DATABASE [estoque] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [estoque] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [estoque] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [estoque] SET ACCELERATED_DATABASE_RECOVERY = OFF  

ALTER DATABASE [estoque] SET QUERY_STORE = ON

ALTER DATABASE [estoque] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)

USE [estoque]

/****** Object:  Table [dbo].[ItemMovimentado]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[ItemMovimentado](
	[idMovimento] [int] NOT NULL,
	[idProduto] [int] NOT NULL,
	[quantidade] [int] NOT NULL,
	[precoUnitario] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idMovimento] ASC,
	[idProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Movimento]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Movimento](
	[idMovimento] [int] IDENTITY(1,1) NOT NULL,
	[idUsuario] [int] NOT NULL,
	[idPessoa] [int] NOT NULL,
	[tipoMovimento] [char](1) NULL,
	[dataMovimento] [datetime] NULL,
	[valorTotal] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idMovimento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Pessoa]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Pessoa](
	[idPessoa] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](255) NOT NULL,
	[logradouro] [varchar](255) NULL,
	[cidade] [varchar](255) NULL,
	[estado] [char](2) NULL,
	[telefone] [varchar](11) NULL,
	[email] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[idPessoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[PessoaFisica]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[PessoaFisica](
	[idPessoa] [int] NOT NULL,
	[cpf] [char](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idPessoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[cpf] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[PessoaJuridica]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[PessoaJuridica](
	[idPessoa] [int] NOT NULL,
	[cnpj] [char](14) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idPessoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[cnpj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Produto]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Produto](
	[idProduto] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](255) NOT NULL,
	[quantidade] [int] NOT NULL,
	[precoVenda] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Usuario]    Script Date: 30/03/2025 19:26:06 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Usuario](
	[idUsuario] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](255) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[senha] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[Movimento] ADD  DEFAULT (getdate()) FOR [dataMovimento]

ALTER TABLE [dbo].[Produto] ADD  DEFAULT ((0)) FOR [quantidade]

ALTER TABLE [dbo].[ItemMovimentado]  WITH CHECK ADD FOREIGN KEY([idMovimento])
REFERENCES [dbo].[Movimento] ([idMovimento])
ON DELETE CASCADE

ALTER TABLE [dbo].[ItemMovimentado]  WITH CHECK ADD FOREIGN KEY([idProduto])
REFERENCES [dbo].[Produto] ([idProduto])
ON DELETE CASCADE

ALTER TABLE [dbo].[Movimento]  WITH CHECK ADD FOREIGN KEY([idPessoa])
REFERENCES [dbo].[Pessoa] ([idPessoa])

ALTER TABLE [dbo].[Movimento]  WITH CHECK ADD FOREIGN KEY([idUsuario])
REFERENCES [dbo].[Usuario] ([idUsuario])

ALTER TABLE [dbo].[PessoaFisica]  WITH CHECK ADD FOREIGN KEY([idPessoa])
REFERENCES [dbo].[Pessoa] ([idPessoa])
ON DELETE CASCADE

ALTER TABLE [dbo].[PessoaJuridica]  WITH CHECK ADD FOREIGN KEY([idPessoa])
REFERENCES [dbo].[Pessoa] ([idPessoa])
ON DELETE CASCADE

ALTER TABLE [dbo].[Movimento]  WITH CHECK ADD  CONSTRAINT [CK_Movimento_tipoMovimento] CHECK  (([tipoMovimento]='S' OR [tipoMovimento]='E' OR [tipoMovimento]='V' OR [tipoMovimento]='C'))

ALTER TABLE [dbo].[Movimento] CHECK CONSTRAINT [CK_Movimento_tipoMovimento]

USE [master]

ALTER DATABASE [estoque] SET  READ_WRITE 

